spring.application.name=lab7spring

server.servlet.context-path=/DemoSpring
server.port=8082

spring.datasource.url=jdbc:sqlserver://DESKTOP-TC60A93;instanceName=SQLEXPRESS;databaseName=PhoneStationDB;encrypt=true;trustServerCertificate=true;
spring.datasource.username=lab1u
spring.datasource.password=lab1uPass
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql=true

spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false
